version: "3.6"
services:
  database:
    image: mongo
    container_name: "database"
    command: [--auth]
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - backend
  api:
    container_name: "api"
    image: daoventures/api-app:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - "./config:/api/config:ro"
      - "./services:/api/services:ro"
      - "./utils:/api/utils:ro"
      - "./models:/api/models:ro"
    networks:
      - backend
volumes:
  mongodata:
networks:
  backend:
    driver: bridge
